# Generated by Django 3.2.12 on 2022-10-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('PN', 'pending'), ('BL', 'block'), ('DN', 'done')], default='pn', max_length=2),
        ),
    ]
